apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: argo-executor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-executor-role
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: default
